"""
runtime/source_patcher.py
64-bit Android NDK porting patcher + Runtime Asset Stubber.

Responsibility: 
1. Fix 64-bit C compliance (pointers, casts, assertions).
2. Stub missing asset headers to allow building without a baserom.gba.
"""

import os
import re
import sys

# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────

def read_file(path: str) -> str:
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        return fh.read()

def write_file(path: str, content: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)

def patch_summary(label: str, original: str, patched: str) -> None:
    if original != patched:
        print(f"  [PATCHED] {label}")
    else:
        print(f"  [skip]    {label}  (no changes needed)")

# ──────────────────────────────────────────────────────────────────────────────
# 0. Asset Stubbing (For SAF Runtime Loading)
# ──────────────────────────────────────────────────────────────────────────────

def stub_asset_headers(include_dir: str = "include"):
    """
    Creates dummy offset headers if they are missing. 
    This allows the NDK to compile without needing the baserom at build-time.
    """
    asset_dir = os.path.join(include_dir, "assets")
    if not os.path.exists(asset_dir):
        os.makedirs(asset_dir)
        print(f"  [MKDIR]   {asset_dir}")
        
    headers = ["map_offsets.h", "gfx_offsets.h"]
    for h in headers:
        path = os.path.join(asset_dir, h)
        if not os.path.exists(path):
            print(f"  [STUB]    Creating {path} (SAF Runtime Compatibility)")
            stub_content = (
                "#ifndef ASSET_OFFSETS_H\n"
                "#define ASSET_OFFSETS_H\n\n"
                "// Generated by patcher for runtime SAF ROM decompression.\n"
                "// These offsets are usually scanned from a ROM, but we define\n"
                "// them as 0 or stubs to allow the engine to compile.\n\n"
                "#endif\n"
            )
            write_file(path, stub_content)

# ──────────────────────────────────────────────────────────────────────────────
# 1. Entry point + virtual register stubs (src/main.c)
# ──────────────────────────────────────────────────────────────────────────────

MAIN_HEADER = "#include <stdint.h>\nextern uint16_t* get_virtual_reg();\n"
MAIN_FOOTER = "\nvoid main_step(void) { /* Hooked by JNI */ }\n"

def patch_main_c(src_dir: str = "src") -> None:
    path = os.path.join(src_dir, "main.c")
    if not os.path.exists(path):
        return

    content = read_file(path)
    original = content
    if "get_virtual_reg" in content and "main_step" in content:
        return

    content = content.replace("int main(void)", "void main_init(void)")
    content = re.sub(
        r'\(u16\s*\*\s*\)\s*0x0400[0-9A-Fa-f]+',
        '((u16*)get_virtual_reg())',
        content
    )
    if MAIN_HEADER.strip() not in content:
        content = MAIN_HEADER + content
    if "main_step" not in content:
        content += MAIN_FOOTER

    patch_summary(path, original, content)
    write_file(path, content)

# ──────────────────────────────────────────────────────────────────────────────
# 2. Modernise static_assert macro (include/global.h)
# ──────────────────────────────────────────────────────────────────────────────

OLD_ASSERT_RE = re.compile(
    r'#\s*define\s+static_assert\s*\(cond\)\s+'
    r'extern\s+char\s+assertion\s*\[\s*\(cond\)\s*\?\s*1\s*:\s*-1\s*\]',
    re.MULTILINE
)
NEW_ASSERT = '#define static_assert(cond) _Static_assert(cond, "Dimension Mismatch")'

def patch_global_h(include_dir: str = "include") -> None:
    path = os.path.join(include_dir, "global.h")
    if not os.path.exists(path):
        return

    content = read_file(path)
    original = content
    if "_Static_assert" in content:
        return

    content = OLD_ASSERT_RE.sub(NEW_ASSERT, content)
    if "#include <stdint.h>" not in content:
        content = "#include <stdint.h>\n" + content

    patch_summary(path, original, content)
    write_file(path, content)

# ──────────────────────────────────────────────────────────────────────────────
# 3. Relax sizeof assertions (== to >=)
# ──────────────────────────────────────────────────────────────────────────────

SIZEOF_ASSERT_RE = re.compile(
    r'static_assert\s*\(\s*sizeof\s*\(\s*(.*?)\s*\)\s*==\s*([0-9A-Za-z_x]+)\s*\)',
    re.DOTALL
)

def patch_sizeof_assertions(include_dir: str = "include") -> None:
    for root, _, files in os.walk(include_dir):
        for fname in files:
            if not fname.endswith(".h"): continue
            path = os.path.join(root, fname)
            content = read_file(path)
            patched = SIZEOF_ASSERT_RE.sub(
                lambda m: f'static_assert(sizeof({m.group(1)}) >= {m.group(2)})',
                content
            )
            if patched != content:
                patch_summary(path, content, patched)
                write_file(path, patched)

# ──────────────────────────────────────────────────────────────────────────────
# 4. Pointer-truncation fix: (u32)expr to (uintptr_t)(expr)
# ──────────────────────────────────────────────────────────────────────────────

U32_CAST_RE = re.compile(
    r'\(u32\)\s*([A-Za-z_][A-Za-z0-9_.>-]*(?:\[[^\]]*\])*)'
)

def patch_u32_casts(src_dir: str = "src") -> None:
    for root, _, files in os.walk(src_dir):
        for fname in files:
            if not fname.endswith(".c"): continue
            path = os.path.join(root, fname)
            content = read_file(path)
            if "(u32)" not in content: continue
            patched = U32_CAST_RE.sub(r'(uintptr_t)(\1)', content)
            if patched != content:
                patch_summary(path, content, patched)
                write_file(path, patched)

# ──────────────────────────────────────────────────────────────────────────────
# 5. Rewrite lvalue casts: (TYPE*)ptr += n to ptr = (void*)((TYPE*)ptr + n)
# ──────────────────────────────────────────────────────────────────────────────

LVALUE_CAST_RE = re.compile(
    r'\(\s*([A-Za-z_][A-Za-z0-9_\s*]*?)\s*\*\s*\)\s*'
    r'([A-Za-z_][A-Za-z0-9_.>-]*)'
    r'\s*\+=\s*'
    r'([^;]+?)\s*;',
    re.MULTILINE
)

def _rewrite_lvalue_cast(m: re.Match) -> str:
    return f'{m.group(2).strip()} = (void*)(({m.group(1).strip()}*){m.group(2).strip()} + ({m.group(3).strip()}));'

def patch_lvalue_casts(src_dir: str = "src") -> None:
    for root, _, files in os.walk(src_dir):
        for fname in files:
            if not fname.endswith(".c"): continue
            path = os.path.join(root, fname)
            content = read_file(path)
            if "*)" not in content or "+=" not in content: continue
            patched = LVALUE_CAST_RE.sub(_rewrite_lvalue_cast, content)
            if patched != content:
                patch_summary(path, content, patched)
                write_file(path, patched)

# ──────────────────────────────────────────────────────────────────────────────
# Execution
# ──────────────────────────────────────────────────────────────────────────────

def patch_source(src_dir="src", include_dir="include"):
    print("=== Step 0: Stubbing Asset Headers for Runtime ROM Loading ===")
    stub_asset_headers(include_dir)

    print("\n=== Step 1: Patching Entry Point & Registers ===")
    patch_main_c(src_dir)

    print("\n=== Step 2: Modernizing global.h Assertions ===")
    patch_global_h(include_dir)

    print("\n=== Step 3: Relaxing sizeof Constraints ===")
    patch_sizeof_assertions(include_dir)

    print("\n=== Step 4: Fixing Pointer Truncation ===")
    patch_u32_casts(src_dir)

    print("\n=== Step 5: Rewriting LValue Casts ===")
    patch_lvalue_casts(src_dir)

    print("\n64-bit Porting Patch Applied Successfully.")

if __name__ == "__main__":
    patch_source()
