#include <jni.h>
#include <string>
#include <unistd.h>
#include <android/log.h>
#include <fcntl.h>
#include <vector>
#include "assets.h" // Generated by your python script

#define LOG_TAG "MinishNative"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

// External references to the decompiled source
extern "C" {
    // These must match the function signatures in tmca/src
    void main_init(void); 
    void main_step(void);
}

// Global buffer representing GBA VRAM (240x160 16-bit pixels)
uint16_t g_vram_buffer[240 * 160];

void ExtractAssets(int fd) {
    LOGI("Starting extraction of %d assets...", ASSET_COUNT);
    for (int i = 0; i < ASSET_COUNT; i++) {
        AssetMetadata asset = g_AssetTable[i];
        
        // Seek to the specific ROM offset
        if (lseek(fd, asset.offset, SEEK_SET) == -1) continue;

        // In a real implementation, you would write these to the app's internal 
        // storage (/data/data/com.minish.ndk/files/) so the C engine can 
        // access them via standard fopen() calls later.
        std::vector<char> buffer(asset.size);
        read(fd, buffer.data(), asset.size);
        
        // LOGI("Extracted: %s (%u bytes)", asset.name, asset.size);
    }
    LOGI("Extraction complete.");
}

extern "C" {

    JNIEXPORT void JNICALL
    Java_com_minish_ndk_MainActivity_initGameWithRom(JNIEnv* env, jobject thiz, jint fd) {
        LOGI("Received ROM File Descriptor: %d", fd);

        char gameCode[5] = {0};
        lseek(fd, 0xAC, SEEK_SET);
        if (read(fd, gameCode, 4) != 4) return;

        if (std::string(gameCode).find("BZL") != 0) {
            LOGE("Validation Failed: %s", gameCode);
            return;
        }

        LOGI("ROM Validated: %s", gameCode);

        // 1. Extract data for the engine to use
        ExtractAssets(fd);

        // 2. Initialize the Minish Cap engine logic
        // main_init(); 
    }

    // This function should be called by a Choreographer or GameLoop thread in Kotlin
    JNIEXPORT void JNICALL
    Java_com_minish_ndk_MainActivity_onFrameTick(JNIEnv* env, jobject thiz) {
        // 1. Advance the game state by one frame
        // main_step();

        // 2. Map the game's internal palette/tiles to g_vram_buffer
        // UpdateVideo(g_vram_buffer);
    }

    // Used by the Kotlin side to get the address of our pixel buffer
    JNIEXPORT jpointer JNICALL
    Java_com_minish_ndk_MainActivity_getVideoBuffer(JNIEnv* env, jobject thiz) {
        return (jpointer)g_vram_buffer;
    }
}
